-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select "customer id", "purchase_amount"
from customer
where "discount applied" = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select "item purchased", AVG("review rating") as "Average Product Rating"
from customer
group by "item purchased"
order by avg("review rating") desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select "shipping type",
ROUND(AVG(purchase_amount),2)
from customer
where "shipping type" in ('Standard', 'Express')
group by "shipping type"

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
select "subscription status",
COUNT ("customer id") as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND (SUM(purchase_amount) ,2) as total_revenue
from customer
group by "subscription status"
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select "item purchased",
ROUND(100 * SUM(CASE WHEN "discount applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by "item purchased"
order by discount_rate desc
limit 5;
I
-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
with customer_type as (
select "customer id", "previous purchases",
CASE
WHEN "previous purchases" = 1 THEN 'New'
WHEN "previous purchases" BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
from customer)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
"item purchased",
COUNT ("customer id") as total_orders,
ROW_NUMBER() over (partition by category order by count("customer id") DESC) as item_rank
from customer
group by category, "item purchased")
select item_rank, category, "item purchased", total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select "subscription status",
count("customer id") as repeat_buyers
from customer
where "previous purchases" > 5
group by  "subscription status"

-- Q1e. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;